RemCua.Web/Controllers/ProductCategoryController.cs
using RemCua.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RemCua.Web.Controllers
{
    public class ProductCategoryController : Controller
    {
        private IProductCategoryService _productCategoryService;
        public ProductCategoryController(IProductCategoryService productCategoryService)
        {
            this._productCategoryService = productCategoryService;
        }
        [ChildActionOnly]
        //[OutputCache(Duration = 3600)]
        public PartialViewResult _ProductCategory()
        {
            var model = _productCategoryService.GetAll();
            return PartialView(model);
        }
    }
}

RemCua.Web/Controllers/ProductController.cs
using RemCua.Common;
using RemCua.Entities.Models;
using RemCua.Service;
using RemCua.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RemCua.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductCategoryService _productCategoryService;
        private readonly IPostService _postService;
        public ProductController(IProductService productService, IProductCategoryService productCategoryService, IPostService postService)
        {
            this._productService = productService;
            this._productCategoryService = productCategoryService;
            this._postService = postService;
        }
        // GET: Product
        public ActionResult Detail(int id)
        {
            ViewBag.ReatedProduct = _productService.GetReatedProduct(id, 4);//Hiển Thị theo ViewBag
            ViewBag.Feature = _productService.ListFeatureProduct(10);
            var model = _productService.GetById(id);
            return View(model);
        }
        public ActionResult Category(int id, int page = 1)
        {
            int pageSize = 16;
            int totalRow = 0;
            var productModel = _productService.GetListProductByCategoryIdPaging(id, page, pageSize, out totalRow);
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            var paginationSet = new PaginationSet<Product>()
            {
                Items = productModel,
                Page = page,
                MaxPage=5,
                TotalCount = totalRow,
                TotalPages = totalPage
            };
            ViewBag.Category = _productCategoryService.GetById(id);
            ViewBag.NewPost = _postService.GetNewPost(6);
            ViewBag.Feature = _productService.ListFeatureProduct(10);
            return View(paginationSet);
        }
        public ActionResult Search(string keyword, int page = 1, string sort = "")
        {
            int pageSize = 16;
            int totalRow = 0;
            var productModel = _productService.Search(keyword, page, pageSize, out totalRow);
            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);

            ViewBag.Keyword = keyword;
            var paginationSet = new PaginationSet<Product>()
            {
                Items = productModel,
                MaxPage = 5,
                Page = page,
                TotalCount = totalRow,
                TotalPages = totalPage
            };
            ViewBag.NewPost = _postService.GetNewPost(6);
            ViewBag.Feature = _productService.ListFeatureProduct(10);
            return View(paginationSet);
        }
    }
}

RemCua.Web/Controllers/SildeController.cs
using RemCua.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RemCua.Web.Controllers
{
    public class SildeController : Controller
    {
        private ISlideService _slideService;
        public SildeController(ISlideService slideService)
        {
            this._slideService = slideService;
        }
        // GET: Silde
        [ChildActionOnly]
        //[OutputCache(Duration = 3600)]
        public PartialViewResult _Slide()
        {
            var model = _slideService.GetAll();
            return PartialView(model);
        }
    }
}

RemCua.Web/Views/Shared/_Ads.cshtml
<div>
    <div class="box-ads">
        <div class="row-module_ads">
            <div class="module_ads">
                <img src="~/Content/Client/img/VIDEOREMCUA.jpg" />
                <img src="~/Content/Client/img/Capture.PNG" />
            </div>
        </div>
    </div>
</div>

RemCua.Web/Views/Shared/_Footer.cshtml
<div class="wrapper-footer">
    <div class="footer-shop-name">
        <div class="col-footer">
            <div class="col-footer-w25">
                <ul>
                    <li><a href="#"><i class="fa fa-angle-double-right">&nbsp;</i>SHOWROOM 39 KHUẤT DUY TIẾN – HÀ NỘI</a></li>
                    <li><a href="#"><i class="fa fa-university"></i>CÔNG TY CP DVTM & XD BẠCH DƯƠNG</a></li>
                    <li><a href="#"><i class="fa fa-location-arrow"></i>Địa chỉ: Số 39 Khuất Duy Tiến - Thanh Xuân</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i>Điện thoại: 0432.222.660 - 0987.818.912</a></li>
                    <li>
                        <a href="#"><i class="fa fa-envelope"></i>Email: rembachduong@gmail.com</a>
                    </li>
                </ul>
                
            </div>
            <div class="col-footer-w25">
                <ul>
                    <li><a href="#"><i class="fa fa-angle-double-right">&nbsp;</i>SHOWROOM 16 TỐ HỮU – HÀ NỘI</a></li>
                    <li><a href="#"><i class="fa fa-university"></i>CÔNG TY CP DVTM & XD BẠCH DƯƠNG</a></li>
                    <li><a href="#"><i class="fa fa-location-arrow"></i>Địa chỉ: Số 16 Tố Hữu - Vạn Phúc – Hà Đông</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i>Điện thoại: 0433.520.291 - 0987.818.912</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i>Email: rembachduong@gmail.com</a></li>
                </ul>
            </div>
            <div class="col-footer-w25">
                <ul>
                    <li><a href="#"><i class="fa fa-angle-double-right">&nbsp;</i>SHOWROOM GÒ DẦU – TP HỒ CHÍ MINH</a></li>
                    <li><a href="#"><i class="fa fa-university"></i>CÔNG TY CP DVTM & XD BẠCH DƯƠNG</a></li>
                    <li><a href="#"><i class="fa fa-location-arrow"></i>Địa chỉ: /68 Gò Dầu - P.Tân Quý - Q. Tân Phú</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i>Điện thoại: 0987.818.912 - 0904.558.766</a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i>Email: rembachduong@gmail.com</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

RemCua.Web/Views/Shared/_Header.cshtml
 <!---Begin topBar-->
<div id="topBar">
    <div class="wrapper-topbar clearfix">
        <ul class="toolbar-cus clearfix">
            <li><a title="Trang chủ" href="/trang-chu">Trang chủ</a></li>
            <li><a title="Tin tức" href="/tin-tuc">Tin tức</a></li>
            <li><a title="Liên hệ" href="/trang/lien-he">Liên hệ</a></li>
            <li><a title="Bản đồ" href="/trang/gioi-thieu">Giới thiệu</a></li>
            <li class="bar_cart"><a id="hplCartHeaderMenu" href="/gio-hang"><span id="lblCartMenu" class="counter">0</span></a></li>
        </ul>
    </div>
</div>
<!--EndTopBar-->
<!---Begin header-bootom-->
<div class="header-bottom">
    <div class="wrapper-header-bottom clearfix">
        <div class="logo">
            <a href="/trang-chu">
                <img src="~/Content/Client/img/logo_phuc.png" />
            </a>
        </div>
        <div class="nav-menu">
            <ul class="item-main clearfix">
                <li class="nav-1"><a href="/tin-tuc" class="first top-link"><span><b>Tin Tức</b></span></a></li>
                <li class="nav-3"><a href="/trang/gioi-thieu" class="top-link "><span><b>Giới thiệu</b></span></a></li>
                <li class="nav-4"><a href="/trang/lien-he" class="top-link "><span><b>Liên hệ</b></span></a></li>
                <li class="nav-5"><a href="/gio-hang" class="last top-link"><span><b>Giỏ Hàng</b></span></a></li>
                <li id="searchmenu">
                    @using (Html.BeginForm("Search", "Product", FormMethod.Post))
                    {
                        <input type="text" value="Tìm kiếm..." id="keyword" name="keyword" class="search-input" onfocus="if (this.value=='Tìm kiếm...') this.value='';" onblur="if (this.value=='') this.value='Tìm kiếm...';">
                        <button type="submit" class="search-button"></button>
                    }
                </li>


            </ul>
        </div>
    </div>
</div>
<!--End header-bootom-->

RemCua.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Shop Rem Cua</title>
    <meta charset="utf-8" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Content/js")
    <script type="text/javascript">

        $(window).load(function () {
            $('#slider').nivoSlider({
                effect: 'random',                 // Specify sets like: 'fold,fade,sliceDown'
                slices: 15,                       // For slice animations
                boxCols: 8,                       // For box animations
                boxRows: 4,                       // For box animations
                animSpeed: 500,                   // Slide transition speed
                pauseTime: 3000,                  // How long each slide will show
                startSlide: 0,                    // Set starting Slide (0 index)
                directionNav: false,               // Next & Prev navigation
                controlNav: false,                 // 1,2,3... navigation
                controlNavThumbs: false,          // Use thumbnails for Control Nav
                pauseOnHover: true,               // Stop animation while hovering
                manualAdvance: false,             // Force manual transitions
                randomStart: false,               // Start on a random slide
            });
            $('.colorbox').colorbox({
                overlayClose: true,
                opacity: 0.4,
                rel: "colorbox"
            });
        });
    </script>
    
</head>
<body>
    <div class="wrapper">
        <!---Begin Header-->
        <header>
            @RenderPage("_Header.cshtml")
        </header>
        <!--End Header-->
        <!---Begin Content-->
        <div class="main-content clearfix">
            <div class="wrapper-main">
                <div class="content-inner clearfix">
                    <div id="Breadcrum">
                        <div>
                            @{Html.RenderAction("_Slide", "Silde");}
                        </div>
                        @{Html.RenderAction("_ProductCategory", "ProductCategory");}
                    </div>
                </div>
                <div class="clearfix"></div>
                @RenderBody()
            </div>
        </div>
        <!--End Content-->
        <!---Begin Footer-->
        <footer>
            @RenderPage("_Footer.cshtml")
        </footer>
        <!--End Footer-->
    </div>
</body>
</html>
<!--Start of Zopim Live Chat Script-->
@*<script type="text/javascript">
        window.$zopim || (function (d, s) {
            var z = $zopim = function (c) { z._.push(c) }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0]; z.set = function (o) {
                z.set.
                _.push(o)
            }; z._ = []; z.set._ = []; $.async = !0; $.setAttribute("charset", "utf-8");
            $.src = "//v2.zopim.com/?46sAbxRaGnFl6mkwFKkzk9VDvjHl8kWR"; z.t = +new Date; $.
            type = "text/javascript"; e.parentNode.insertBefore($, e)
        })(document, "script");
</script>*@
<!--End of Zopim Live Chat Script-->

RemCua.Web/Views/Shared/_ProductCategory.cshtml
@model IEnumerable<RemCua.Entities.Models.ProductCategory>


<div class="module box product-category clearfix">
    <div class="module-header">
        <h3><span>Danh mục sản phẩm</span></h3>
    </div>
    @foreach (var item in Model.Where(x => x.ParentID == null))
    {
        var url = "/san-pham/" + item.Alias + "-" + item.ID;
        var childProductCategory = Model.Where(x => x.ParentID == item.ID);
        <ul class="nav-main for-home">
            <li class="category">
                <strong><a title="@item.Name" href="@url">@item.Name</a></strong>
                @if (childProductCategory.Count() > 0)
                {
                    <div class="sub-cate">
                        <div class="subCate">
                            <h2>
                                <a title="Danh Mục" href="">Danh Mục</a>
                            </h2>
                            @foreach (var itemchild in childProductCategory)
                            {
                                var childUrl = "/san-pham/" + itemchild.Alias + "-" + itemchild.ID;
                                <ul>
                                    <li>
                                        <a title="Marketing - Bán Hàng" href="@childUrl">@itemchild.Name</a>
                                    </li>
                                </ul>
                            }
                        </div>
                    </div>
                }
            </li>
        </ul>
    }
    @*<ul class="nav-main for-home">
            <li class="category">
                <strong><a id="hlParentCategory" title="Sách Chuyên Ngành" href="#">Rèm Ngủ</a></strong><div class="guide">
                    <a title="Danh Mục" href="#">Danh Mục,</a>
                    <a title="Tác Giả" href="#">Tác Giả,</a>
                    <a title="Nhà Phát Hành" href="#">Nhà Phát Hành,</a>
                </div>
                <div class="sub-cate">
                    <div class="subCate">
                        <h2><a title="Danh Mục" href="#">Danh Mục</a></h2><ul>
                            <li><a title="Cầu Đường" href="#">Cầu Đường</a></li>
                            <li><a title="Cơ Khí - Chế Tạo Máy" href="#">Cơ Khí - Chế Tạo Máy</a></li>
                            <li><a title="Dầu Khí" href="">Dầu Khí</a></li>
                            <li><a title="Kỹ Thuật Công Nghệ" href="">Kỹ Thuật Công Nghệ</a></li>
                            <li><a title="Môi Trường" href="">Môi Trường</a></li>
                        </ul>
                    </div>
                    <div class="subCate">
                        <h2><a title="Tác Giả" href="">Tác Giả</a></h2><ul>
                            <li><a title="Nhiều Tác Giả" href="">Nhiều Tác Giả</a></li>
                            <li><a title="Nguyễn Kim Dân" href="">Nguyễn Kim Dân</a></li>
                            <li><a title="Hà Sơn" href="">Hà Sơn</a></li>
                            <li><a title="Nhiều Dịch Giả" href="">Nhiều Dịch Giả</a></li>
                            <li>
                                <a title="Thích Nhất Hạnh" href="">Thích Nhất Hạnh</a>
                            </li>
                        </ul>
                    </div>
                    <div class="subCate">
                        <h2><a title="Nhà Phát Hành" href="">Nhà Phát Hành</a></h2><ul>
                            <li><a title="Văn Lang" href="">Văn Lang</a></li>
                            <li><a title="Thăng Long" href="">Thăng Long</a></li>
                            <li><a title="NXB KHKT" href="">NXB KHKT</a></li>
                            <li><a title="Nxb Trẻ " href="">Nxb Trẻ </a></li>
                            <li>
                                <a title="Quang Minh" href="">Quang Minh</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>*@
</div>

RemCua.Web/Views/Shared/_Slide.cshtml
@model IEnumerable<RemCua.Entities.Models.Slide>

<div class="slider-wrapper">
    <div id="slider" class="nivoSlider">
        @foreach (var item in Model)
        {
            <img src="@item.Image" />
            <img src="@item.Image" />
        }
        <img src="~/Content/Client/img/8401-1735428.png" />
        <img src="~/Content/Client/img/8401-1735427.png" />
    </div>
</div>

RemCua.Web/Views/Shared/_SupportOnline.cshtml
<div>
    <div class="title_module">
        <h3 class=""><span>Hỗ Trợ Trực Tuyến</span></h3>
    </div>
    <div class="box-content">
        <div class="row-module_support">
            <div class="module_support">
                <div class="policy_sendo">
                    <div class="policy_sendo_box ">
                        <a class="buystep" href="" title="Các bước mua hàng">Các bước mua hàng</a>
                    </div>
                    <div class="policy_sendo_box">
                        <a class="shippingstep" href="" title="Phương thức vận chuyển">Phương thức vận chuyển</a>
                    </div>
                    <div class="policy_sendo_box">
                        <a class="paymentstep" href="" title="Cách thức thanh toán">Cách thức thanh toán</a>
                    </div>
                </div>
                <div class="help_all nologin">
                    <div class="cs">
                        <div class="title">hỗ trợ khách hàng</div>
                        <div class="phoneno clearfix">
                            <div class="pnleft">
                                <div class="hnphone">
                                    <img src="~/Content/Client/img/hotline.gif" />
                                    <font style="font-size:23px" color="red">0965207749</font>
                                </div>
                                <div class="hnphone">
                                    <img src="~/Content/Client/img/hotline.gif" />
                                    <font style="font-size:23px" color="red">0965207749</font>
                                </div>
                            </div>
                        </div><div class="email">
                            Email: <a href="#" title="Email hỗ trợ của sendo.vn">remcuatot@gmail.com</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>